### ISSUE TITLE
Running web_demo

### ISSUE THREAD

**Issue by Minashraf** [farrell236/RATCHET#1]
I get a
> "No Pretrained Densenet-121 weights specified"
![image](https://user-images.githubusercontent.com/46136768/142381593-4999de3f-8ede-4ee5-9d70-b407a683867e.png)

**Comment by farrell236** [comment]
When the Transformer is first being created, it instantiates the Encoder class which creates a DenseNet from Keras applications. If you have pre-trained weights at hand, that's where it's being loaded. 

The entire Transformer model checkpoint contains weights for the DenseNet encoder, so that (debug) message can be safely ignored.

**Comment by Minashraf** [comment]
I added both v1 and v2 pretrained weight so I should be safe right?

**Comment by farrell236** [comment]
- v1 of the weights are the ones used in the published paper so it can be reproducible ([springer](https://link.springer.com/chapter/10.1007%2F978-3-030-87234-2_28), [arxiv](https://arxiv.org/abs/2107.02104)).
- v2 is RATCHET retrained on a richer text corpus (hopefully better performance?)

**Comment by Minashraf** [comment]
So should I put both in the checkpoints folder or is only v2 enough?

**Comment by farrell236** [comment]
Just one version of the checkpoint per folder, you then specify the folder location [here](https://github.com/farrell236/RATCHET/blob/7a74c2dc6e60aa50b84d8978eefb9d79f0439ef9/web_demo.py#L17) and [here](https://github.com/farrell236/RATCHET/blob/7a74c2dc6e60aa50b84d8978eefb9d79f0439ef9/web_demo.py#L45).

**Comment by Minashraf** [comment]
I unzipped both and the folder structure looks as follows leaving the code as it is, so is it right?
![image](https://user-images.githubusercontent.com/46136768/142386620-a4dc5638-8b62-4352-8a15-d91560c30965.png)

**Comment by farrell236** [comment]
it should be like this:
```
bh1511@armada:~/streamlit/RATCHET$ tree checkpoints/
checkpoints/
├── cxr_validator_model.h5
├── ratchet_model_weights_202009251103.zip
└── train0
    ├── checkpoint
    ├── ckpt-12.data-00000-of-00001
    └── ckpt-12.index

1 directory, 5 files
```

We have a hosted live demo of RATCHET with v1 weights here: http://ratchet.lucidifai.com/

**Comment by Minashraf** [comment]
That's great, because I think it will take a long time to run it on colab free edition, thank you !
