### ISSUE TITLE
How to train or evaluate the model?

### ISSUE THREAD

**Issue by Minashraf** [farrell236/RATCHET#2]
Considering the training and evaluating the model, how can it be done?
I tried to evaluate the model using `python3 evaluate.py`  but it looks like there is a missing file
>FileNotFoundError: [Errno 2] No such file or directory: 'preprocessing/mimic/MIMIC_AP_PA_test.csv'

**Comment by farrell236** [comment]
Unfortunately due to data agreement for the MIMIC dataset, I cannot release the train/test/eval CSVs. [Here](https://github.com/farrell236/RATCHET/tree/master/preprocessing/mimic) details the steps you can take to recreate those files.

**Comment by Minashraf** [comment]
Understood, thank you
