### ISSUE TITLE
Used report section

### ISSUE THREAD

**Issue by ChantalMP** [farrell236/RATCHET#4]
Hi! Thanks for your work and publishing your code.
Which section of the report did you predict? The findings or impression section or both? Or the output of the create_section_files.py, which can be either of them depending on what's included in the report.

Thank you in advance!

**Comment by farrell236** [comment]
Hi Chantal! In the paper, we predicted/evaluated on impression only as it was the default setting for create_section_files.py. We later retrained the model on findings (released as v2 weights in this [commit tag](https://github.com/farrell236/RATCHET/tree/6954679f5fe3e336e5515a2de0845a865615867f)). 

Best wishes,
Benjamin

**Comment by ChantalMP** [comment]
Thank you for your quick reply :)
